//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.225
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.Users {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfUsers", Namespace="http://tempuri.org/", ItemName="users")]
    [System.SerializableAttribute()]
    public class ArrayOfUsers : System.Collections.Generic.List<NWC.Users.users> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="users", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string roleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string pass {
            get {
                return this.passField;
            }
            set {
                if ((object.ReferenceEquals(this.passField, value) != true)) {
                    this.passField = value;
                    this.RaisePropertyChanged("pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string role {
            get {
                return this.roleField;
            }
            set {
                if ((object.ReferenceEquals(this.roleField, value) != true)) {
                    this.roleField = value;
                    this.RaisePropertyChanged("role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Users.UsersSoap")]
    public interface UsersSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем login из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Check", ReplyAction="*")]
        NWC.Users.CheckResponse Check(NWC.Users.CheckRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем key из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUsers", ReplyAction="*")]
        NWC.Users.UpdateUsersResponse UpdateUsers(NWC.Users.UpdateUsersRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем key из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListUsers", ReplyAction="*")]
        NWC.Users.ListUsersResponse ListUsers(NWC.Users.ListUsersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Check", Namespace="http://tempuri.org/", Order=0)]
        public NWC.Users.CheckRequestBody Body;
        
        public CheckRequest() {
        }
        
        public CheckRequest(NWC.Users.CheckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public CheckRequestBody() {
        }
        
        public CheckRequestBody(string login, string pass) {
            this.login = login;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckResponse", Namespace="http://tempuri.org/", Order=0)]
        public NWC.Users.CheckResponseBody Body;
        
        public CheckResponse() {
        }
        
        public CheckResponse(NWC.Users.CheckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckResult;
        
        public CheckResponseBody() {
        }
        
        public CheckResponseBody(string CheckResult) {
            this.CheckResult = CheckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUsers", Namespace="http://tempuri.org/", Order=0)]
        public NWC.Users.UpdateUsersRequestBody Body;
        
        public UpdateUsersRequest() {
        }
        
        public UpdateUsersRequest(NWC.Users.UpdateUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUsersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public NWC.Users.ArrayOfUsers users;
        
        public UpdateUsersRequestBody() {
        }
        
        public UpdateUsersRequestBody(string key, NWC.Users.ArrayOfUsers users) {
            this.key = key;
            this.users = users;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public NWC.Users.UpdateUsersResponseBody Body;
        
        public UpdateUsersResponse() {
        }
        
        public UpdateUsersResponse(NWC.Users.UpdateUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateUsersResponseBody {
        
        public UpdateUsersResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListUsers", Namespace="http://tempuri.org/", Order=0)]
        public NWC.Users.ListUsersRequestBody Body;
        
        public ListUsersRequest() {
        }
        
        public ListUsersRequest(NWC.Users.ListUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListUsersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        public ListUsersRequestBody() {
        }
        
        public ListUsersRequestBody(string key) {
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public NWC.Users.ListUsersResponseBody Body;
        
        public ListUsersResponse() {
        }
        
        public ListUsersResponse(NWC.Users.ListUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NWC.Users.ArrayOfUsers ListUsersResult;
        
        public ListUsersResponseBody() {
        }
        
        public ListUsersResponseBody(NWC.Users.ArrayOfUsers ListUsersResult) {
            this.ListUsersResult = ListUsersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsersSoapChannel : NWC.Users.UsersSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsersSoapClient : System.ServiceModel.ClientBase<NWC.Users.UsersSoap>, NWC.Users.UsersSoap {
        
        public UsersSoapClient() {
        }
        
        public UsersSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsersSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NWC.Users.CheckResponse NWC.Users.UsersSoap.Check(NWC.Users.CheckRequest request) {
            return base.Channel.Check(request);
        }
        
        public string Check(string login, string pass) {
            NWC.Users.CheckRequest inValue = new NWC.Users.CheckRequest();
            inValue.Body = new NWC.Users.CheckRequestBody();
            inValue.Body.login = login;
            inValue.Body.pass = pass;
            NWC.Users.CheckResponse retVal = ((NWC.Users.UsersSoap)(this)).Check(inValue);
            return retVal.Body.CheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NWC.Users.UpdateUsersResponse NWC.Users.UsersSoap.UpdateUsers(NWC.Users.UpdateUsersRequest request) {
            return base.Channel.UpdateUsers(request);
        }
        
        public void UpdateUsers(string key, NWC.Users.ArrayOfUsers users) {
            NWC.Users.UpdateUsersRequest inValue = new NWC.Users.UpdateUsersRequest();
            inValue.Body = new NWC.Users.UpdateUsersRequestBody();
            inValue.Body.key = key;
            inValue.Body.users = users;
            NWC.Users.UpdateUsersResponse retVal = ((NWC.Users.UsersSoap)(this)).UpdateUsers(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NWC.Users.ListUsersResponse NWC.Users.UsersSoap.ListUsers(NWC.Users.ListUsersRequest request) {
            return base.Channel.ListUsers(request);
        }
        
        public NWC.Users.ArrayOfUsers ListUsers(string key) {
            NWC.Users.ListUsersRequest inValue = new NWC.Users.ListUsersRequest();
            inValue.Body = new NWC.Users.ListUsersRequestBody();
            inValue.Body.key = key;
            NWC.Users.ListUsersResponse retVal = ((NWC.Users.UsersSoap)(this)).ListUsers(inValue);
            return retVal.Body.ListUsersResult;
        }
    }
}
