//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.225
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.Players {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfPlayers", Namespace="http://tempuri.org/", ItemName="players")]
    [System.SerializableAttribute()]
    public class ArrayOfPlayers : System.Collections.Generic.List<NWC.Players.players> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="players", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class players : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private System.Nullable<int> PlayerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SponsorTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SponsorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> PlayerId {
            get {
                return this.PlayerIdField;
            }
            set {
                if ((this.PlayerIdField.Equals(value) != true)) {
                    this.PlayerIdField = value;
                    this.RaisePropertyChanged("PlayerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SponsorType {
            get {
                return this.SponsorTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SponsorTypeField, value) != true)) {
                    this.SponsorTypeField = value;
                    this.RaisePropertyChanged("SponsorType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Sponsor {
            get {
                return this.SponsorField;
            }
            set {
                if ((object.ReferenceEquals(this.SponsorField, value) != true)) {
                    this.SponsorField = value;
                    this.RaisePropertyChanged("Sponsor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Team {
            get {
                return this.TeamField;
            }
            set {
                if ((object.ReferenceEquals(this.TeamField, value) != true)) {
                    this.TeamField = value;
                    this.RaisePropertyChanged("Team");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Players.PlayersSoap")]
    public interface PlayersSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем GetAllPlayersResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPlayers", ReplyAction="*")]
        NWC.Players.GetAllPlayersResponse GetAllPlayers(NWC.Players.GetAllPlayersRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetAllPlayers_internalResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPlayers_internal", ReplyAction="*")]
        NWC.Players.GetAllPlayers_internalResponse GetAllPlayers_internal(NWC.Players.GetAllPlayers_internalRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем appkey из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAllPlayers_internal", ReplyAction="*")]
        NWC.Players.UpdateAllPlayers_internalResponse UpdateAllPlayers_internal(NWC.Players.UpdateAllPlayers_internalRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем team из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPlayersFromTeam", ReplyAction="*")]
        NWC.Players.GetAllPlayersFromTeamResponse GetAllPlayersFromTeam(NWC.Players.GetAllPlayersFromTeamRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем PlayerResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Player", ReplyAction="*")]
        NWC.Players.PlayerResponse Player(NWC.Players.PlayerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPlayersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPlayers", Namespace="http://tempuri.org/", Order=0)]
        public NWC.Players.GetAllPlayersRequestBody Body;
        
        public GetAllPlayersRequest() {
        }
        
        public GetAllPlayersRequest(NWC.Players.GetAllPlayersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPlayersRequestBody {
        
        public GetAllPlayersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPlayersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPlayersResponse", Namespace="http://tempuri.org/", Order=0)]
        public NWC.Players.GetAllPlayersResponseBody Body;
        
        public GetAllPlayersResponse() {
        }
        
        public GetAllPlayersResponse(NWC.Players.GetAllPlayersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPlayersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllPlayersResult;
        
        public GetAllPlayersResponseBody() {
        }
        
        public GetAllPlayersResponseBody(string GetAllPlayersResult) {
            this.GetAllPlayersResult = GetAllPlayersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPlayers_internalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPlayers_internal", Namespace="http://tempuri.org/", Order=0)]
        public NWC.Players.GetAllPlayers_internalRequestBody Body;
        
        public GetAllPlayers_internalRequest() {
        }
        
        public GetAllPlayers_internalRequest(NWC.Players.GetAllPlayers_internalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPlayers_internalRequestBody {
        
        public GetAllPlayers_internalRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPlayers_internalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPlayers_internalResponse", Namespace="http://tempuri.org/", Order=0)]
        public NWC.Players.GetAllPlayers_internalResponseBody Body;
        
        public GetAllPlayers_internalResponse() {
        }
        
        public GetAllPlayers_internalResponse(NWC.Players.GetAllPlayers_internalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPlayers_internalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NWC.Players.ArrayOfPlayers GetAllPlayers_internalResult;
        
        public GetAllPlayers_internalResponseBody() {
        }
        
        public GetAllPlayers_internalResponseBody(NWC.Players.ArrayOfPlayers GetAllPlayers_internalResult) {
            this.GetAllPlayers_internalResult = GetAllPlayers_internalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAllPlayers_internalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAllPlayers_internal", Namespace="http://tempuri.org/", Order=0)]
        public NWC.Players.UpdateAllPlayers_internalRequestBody Body;
        
        public UpdateAllPlayers_internalRequest() {
        }
        
        public UpdateAllPlayers_internalRequest(NWC.Players.UpdateAllPlayers_internalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAllPlayers_internalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appkey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public NWC.Players.ArrayOfPlayers players;
        
        public UpdateAllPlayers_internalRequestBody() {
        }
        
        public UpdateAllPlayers_internalRequestBody(string appkey, NWC.Players.ArrayOfPlayers players) {
            this.appkey = appkey;
            this.players = players;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAllPlayers_internalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAllPlayers_internalResponse", Namespace="http://tempuri.org/", Order=0)]
        public NWC.Players.UpdateAllPlayers_internalResponseBody Body;
        
        public UpdateAllPlayers_internalResponse() {
        }
        
        public UpdateAllPlayers_internalResponse(NWC.Players.UpdateAllPlayers_internalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateAllPlayers_internalResponseBody {
        
        public UpdateAllPlayers_internalResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPlayersFromTeamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPlayersFromTeam", Namespace="http://tempuri.org/", Order=0)]
        public NWC.Players.GetAllPlayersFromTeamRequestBody Body;
        
        public GetAllPlayersFromTeamRequest() {
        }
        
        public GetAllPlayersFromTeamRequest(NWC.Players.GetAllPlayersFromTeamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPlayersFromTeamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string team;
        
        public GetAllPlayersFromTeamRequestBody() {
        }
        
        public GetAllPlayersFromTeamRequestBody(string team) {
            this.team = team;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPlayersFromTeamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPlayersFromTeamResponse", Namespace="http://tempuri.org/", Order=0)]
        public NWC.Players.GetAllPlayersFromTeamResponseBody Body;
        
        public GetAllPlayersFromTeamResponse() {
        }
        
        public GetAllPlayersFromTeamResponse(NWC.Players.GetAllPlayersFromTeamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPlayersFromTeamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllPlayersFromTeamResult;
        
        public GetAllPlayersFromTeamResponseBody() {
        }
        
        public GetAllPlayersFromTeamResponseBody(string GetAllPlayersFromTeamResult) {
            this.GetAllPlayersFromTeamResult = GetAllPlayersFromTeamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Player", Namespace="http://tempuri.org/", Order=0)]
        public NWC.Players.PlayerRequestBody Body;
        
        public PlayerRequest() {
        }
        
        public PlayerRequest(NWC.Players.PlayerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlayerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public PlayerRequestBody() {
        }
        
        public PlayerRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayerResponse", Namespace="http://tempuri.org/", Order=0)]
        public NWC.Players.PlayerResponseBody Body;
        
        public PlayerResponse() {
        }
        
        public PlayerResponse(NWC.Players.PlayerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlayerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PlayerResult;
        
        public PlayerResponseBody() {
        }
        
        public PlayerResponseBody(string PlayerResult) {
            this.PlayerResult = PlayerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PlayersSoapChannel : NWC.Players.PlayersSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayersSoapClient : System.ServiceModel.ClientBase<NWC.Players.PlayersSoap>, NWC.Players.PlayersSoap {
        
        public PlayersSoapClient() {
        }
        
        public PlayersSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlayersSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayersSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayersSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NWC.Players.GetAllPlayersResponse NWC.Players.PlayersSoap.GetAllPlayers(NWC.Players.GetAllPlayersRequest request) {
            return base.Channel.GetAllPlayers(request);
        }
        
        public string GetAllPlayers() {
            NWC.Players.GetAllPlayersRequest inValue = new NWC.Players.GetAllPlayersRequest();
            inValue.Body = new NWC.Players.GetAllPlayersRequestBody();
            NWC.Players.GetAllPlayersResponse retVal = ((NWC.Players.PlayersSoap)(this)).GetAllPlayers(inValue);
            return retVal.Body.GetAllPlayersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NWC.Players.GetAllPlayers_internalResponse NWC.Players.PlayersSoap.GetAllPlayers_internal(NWC.Players.GetAllPlayers_internalRequest request) {
            return base.Channel.GetAllPlayers_internal(request);
        }
        
        public NWC.Players.ArrayOfPlayers GetAllPlayers_internal() {
            NWC.Players.GetAllPlayers_internalRequest inValue = new NWC.Players.GetAllPlayers_internalRequest();
            inValue.Body = new NWC.Players.GetAllPlayers_internalRequestBody();
            NWC.Players.GetAllPlayers_internalResponse retVal = ((NWC.Players.PlayersSoap)(this)).GetAllPlayers_internal(inValue);
            return retVal.Body.GetAllPlayers_internalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NWC.Players.UpdateAllPlayers_internalResponse NWC.Players.PlayersSoap.UpdateAllPlayers_internal(NWC.Players.UpdateAllPlayers_internalRequest request) {
            return base.Channel.UpdateAllPlayers_internal(request);
        }
        
        public void UpdateAllPlayers_internal(string appkey, NWC.Players.ArrayOfPlayers players) {
            NWC.Players.UpdateAllPlayers_internalRequest inValue = new NWC.Players.UpdateAllPlayers_internalRequest();
            inValue.Body = new NWC.Players.UpdateAllPlayers_internalRequestBody();
            inValue.Body.appkey = appkey;
            inValue.Body.players = players;
            NWC.Players.UpdateAllPlayers_internalResponse retVal = ((NWC.Players.PlayersSoap)(this)).UpdateAllPlayers_internal(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NWC.Players.GetAllPlayersFromTeamResponse NWC.Players.PlayersSoap.GetAllPlayersFromTeam(NWC.Players.GetAllPlayersFromTeamRequest request) {
            return base.Channel.GetAllPlayersFromTeam(request);
        }
        
        public string GetAllPlayersFromTeam(string team) {
            NWC.Players.GetAllPlayersFromTeamRequest inValue = new NWC.Players.GetAllPlayersFromTeamRequest();
            inValue.Body = new NWC.Players.GetAllPlayersFromTeamRequestBody();
            inValue.Body.team = team;
            NWC.Players.GetAllPlayersFromTeamResponse retVal = ((NWC.Players.PlayersSoap)(this)).GetAllPlayersFromTeam(inValue);
            return retVal.Body.GetAllPlayersFromTeamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NWC.Players.PlayerResponse NWC.Players.PlayersSoap.Player(NWC.Players.PlayerRequest request) {
            return base.Channel.Player(request);
        }
        
        public string Player(int id) {
            NWC.Players.PlayerRequest inValue = new NWC.Players.PlayerRequest();
            inValue.Body = new NWC.Players.PlayerRequestBody();
            inValue.Body.id = id;
            NWC.Players.PlayerResponse retVal = ((NWC.Players.PlayersSoap)(this)).Player(inValue);
            return retVal.Body.PlayerResult;
        }
    }
}
